# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20160224_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeuser',
            name='notes',
        ),
        migrations.AddField(
            model_name='recipeuser',
            name='notes',
            field=models.ManyToManyField(to='recipes.Note'),
        ),
    ]
